services:
  db_api:
    image: mysql:8.0
    networks:
      - gateway
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tp_uscb15
      MYSQL_USER: tp_user
      MYSQL_PASSWORD: tp_pass
    volumes:
      - db_api_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  db_log:
    image: mysql:8.0
    networks:
      - gateway
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tp_log
      MYSQL_USER: log_user
      MYSQL_PASSWORD: log_pass
    volumes:
      - db_log_data:/var/lib/mysql
      - ./sql_log:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./backend
    networks:
      - public
      - gateway
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_api
      DB_PORT: 3306
      DB_NAME: tp_uscb15
      DB_USER: tp_user
      DB_PASS: tp_pass
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db_api:
        condition: service_healthy

  log_service:
    build: ./log_service
    networks:
      - gateway
    environment:
      DB_HOST: db_log
      DB_PORT: 3306
      DB_NAME: tp_log
      DB_USER: log_user
      DB_PASS: log_pass
    depends_on:
      db_log:
        condition: service_healthy

  db_auth:
    image: mysql:8.0
    networks:
      - gateway
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tp_auth
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    volumes:
      - db_auth_data:/var/lib/mysql
      - ./sql_auth:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth_service:
    build: ./auth_service
    networks:
      - public
      - gateway
    ports:
      - "8002:8002"
    environment:
      DB_HOST: db_auth
      DB_PORT: 3306
      DB_NAME: tp_auth
      DB_USER: auth_user
      DB_PASS: auth_pass
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      db_auth:
        condition: service_healthy

networks:
  public:
    driver: bridge
  gateway:
    driver: bridge

volumes:
  db_api_data:
  db_log_data:
  db_auth_data: