services:
  db_api:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tp_uscb15
      MYSQL_USER: tp_user
      MYSQL_PASSWORD: tp_pass
    ports:
      - "3308:3306"
    volumes:
      - db_api_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d:ro

  db_log:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tp_log
      MYSQL_USER: log_user
      MYSQL_PASSWORD: log_pass
    ports:
      - "3309:3306"
    volumes:
      - db_log_data:/var/lib/mysql
      - ./sql_log:/docker-entrypoint-initdb.d:ro

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db_api
      DB_PORT: 3306
      DB_NAME: tp_uscb15
      DB_USER: tp_user
      DB_PASS: tp_pass
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db_api
      - vault

  log_service:
    build: ./log_service
    ports:
      - "8001:8001"
    environment:
      DB_HOST: db_log
      DB_PORT: 3306
      DB_NAME: tp_log
      DB_USER: log_user
      DB_PASS: log_pass
    depends_on:
      - db_log

  db_auth:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tp_auth
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    ports:
      - "3310:3306"
    volumes:
      - db_auth_data:/var/lib/mysql
      - ./sql_auth:/docker-entrypoint-initdb.d:ro

  auth_service:
    build: ./auth_service
    ports:
      - "8002:8002"
    environment:
      DB_HOST: db_auth
      DB_PORT: 3306
      DB_NAME: tp_auth
      DB_USER: auth_user
      DB_PASS: auth_pass
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - db_auth
      - vault

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK

volumes:
  db_api_data:
  db_log_data:
  db_auth_data: